IF %CURRENT_DIR%x == x GOTO SET_PATH
GOTO DONE_PATH
:SET_PATH
SET CURRENT_DIR=%CD%
SET DRIVE_ROOT=%CD:~0,2%
SET NODE_DIR=%DRIVE_ROOT%\ProgramFiles\nodejs
SET PATH=%PATH%;%NODE_DIR%

:DONE_PATH
ECHO Node already set